api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    collection:
        pagination:
            client_enabled: true
            client_items_per_page: true
